### ISSUE TITLE
Doesn’t work with Cascade Layers

### ISSUE THREAD

**Issue by mbarker84** [GoogleChromeLabs/container-query-polyfill#46]
When using a container query within a cascade layer the polyfill no longer works.

This works:

```css
body {
  container-type: inline-size;
}

@container (inline-size > 100px) {
  p {
    background: yellow;
  }
}
```

This doesn’t:

```css
@layer layer1;

@layer layer1 {
  body {
    container-type: inline-size;
  }
	
  @container (inline-size > 100px) {
    p {
      background: yellow;
     }
  }
}
```

Tested in Firefox. Full demo [here](https://codepen.io/michellebarker/pen/LYdvxNg/c3b1b0c9c0bafab1990e48b82083685f).

**Comment by devknoll** [comment]
Thank you for flagging this. I fixed part of the issue in b05f99b and released 0.2.2. I need a little more time to think about a proper fix for the follow up issue, where `container` properties are overridden. I'll follow up here soon.

**Comment by devknoll** [comment]
I merged 3c945dc, which I think will work, though I'll hold off on cutting 0.2.3 until after all of the tests finish running.

On browsers without `@layer` support, the polyfill uses:

```css
* {
  --cq-container-type-XYZ: normal;
  --cq-container-name-XYZ: none;
}
```

This is just meant to prevent the custom variables from cascading between elements by resetting them unless they're explicitly set by something with higher specificity than `*` (0).

On browsers with `@layer` support, it will do the same thing, but wrapped in a base layer:

```css
@layer cq-polyfill-XYZ {
  * {
    --cq-container-type-XYZ: normal;
    --cq-container-name-XYZ: none;
  }
}
```

This _should_ work because any user layers, or rules outside of layers should override these values in the same way. Let me know if you run into any issues though!

**Comment by mbarker84** [comment]
Thanks @devknoll. I’ve updated the [demo](https://codepen.io/michellebarker/pen/VwXNMWQ/1cb757183f10d9be5474fabdfc308fc4) and I can see the styles are being appended as detailed here, but I’m still not seeing the right outcome. On inspection, it seems to be that the `<p>` tag is missing the `data-cqc-XYZ` attribute, it doesn’t appear to be getting applied. If I manually add this in the inspector then the `<p>` has a yellow background as expected.

I thought maybe the Codepen environment was an issue, but it’s the same if I use a plain HTML file. [Here’s the gist](https://gist.github.com/mbarker84/b7fc32340cd99f23bbd823990326b2f4).

**Comment by devknoll** [comment]
I've cut the 0.2.3 release now with the detailed changes, which appears to resolve the issue. Let me know if you run into any further issues!

**Comment by mbarker84** [comment]
Works great, thanks!
